name: Enhanced Python PR Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Display Python version
      run: python -V

    - name: Display working directory
      run: pwd

    - name: List directory contents
      run: ls -la

    - name: Display contents of requirements.txt
      run: cat requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: List installed packages
      run: pip list

    - name: Check code style with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Lint with pylint
      run: |
        pip install pylint
        pylint **/*.py

    - name: Run tests with pytest and check coverage
      run: |
        pip install pytest coverage
        coverage run -m pytest src/tests
        coverage report

    - name: Run pre-commit hooks
      uses: pre-commit/action@v3.0.0

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: src/tests  # Adjust this path as needed

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: .coverage  # Adjust this path if your coverage tool outputs to a different location