# .github/workflows/python-pr.yml

name: Python PR Workflow

on:
  pull_request:
    branches:
      - main  # Run the workflow on pull requests targeting the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code from the PR
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # Specify the Python version you want to use

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Check code style with flake8
    - name: Check code style
      run: |
         pip install flake8
         flake8 .


    # Step 5: Run tests
    - name: Run tests
      run: |
        pip install pytest
        pytest src/tests
