name: Python PR Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run autopep8
      run: |
        pip install autopep8
        autopep8 --in-place --aggressive --aggressive -r src

    # - name: Run tests
    #   run: |
    #     pip install pytest
    #     pytest src/tests

    # You can add more steps here as needed, such as:
    # - Code coverage
    # - Additional linting
    # - Building documentation
    # - Any other checks or processes specific to your project